# Generated by Django 5.1.6 on 2025-03-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
    ]
